name: Build
on:
  push:
    branches:
      - master
      - '*.x'
    tags:
      - '*'
  pull_request:
    branches:
      - master
jobs:
  wheels:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      - uses: joerick/cibuildwheel@v1.9.0
        env:
          CIBW_BUILD: cp36-*
          CIBW_ARCHS_LINUX: auto aarch64
          CIBW_ARCHS_MACOS: auto universal2
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse
